tap "homebrew/bundle"
# tap "homebrew/cask"
tap "homebrew/cask-fonts"
# tap "homebrew/core"
tap "buo/cask-upgrade"

brew "awscli"
brew "bat"
brew "cheat"
# brew "coreutils" # Those that come with macOS are outdated
brew "curl"
brew "eza"  # exa is not maintained
brew "entr"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "htop"
brew "jq"
brew "n"
brew "neovim"
brew "pyenv"
brew "ripgrep"
brew "rsync"
brew "tmux"
brew "tree"
brew "wget"
brew "zoxide"
brew "uv"
# should be handled by oh-my-zsh
# brew "zsh-autosuggestions"
# brew "zsh-completions"
# brew "zsh-syntax-highlighting"

# Fonts
cask "font-fira-code-nerd-font"

# Apps
cask "1password"
cask "alfred"
cask "cleanshot"
cask "docker"
cask "font-hack-nerd-font"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "postman"
cask "rectangle"
cask "slack"
cask "spotify"
cask "telegram"
cask "visual-studio-code"
cask "vlc"
